let lyrics = [
  { seconds: 71, lyrics: "Say your prayers little one" },
  { seconds: 73, lyrics: "Don't forget my son" },
  { seconds: 74, lyrics: "To include everyone" },
  { seconds: 78, lyrics: "I Tuck you in warm within" },
  { seconds: 80, lyrics: "Keep you free from sin" },
  { seconds: 82, lyrics: "Till the sandman he comes" },
  { seconds: 86, lyrics: "Sleep with one eye open" },
  { seconds: 90, lyrics: "Gripping your pillow tight" },
  { seconds: 93, lyrics: "Exit light" },
  { seconds: 97, lyrics: "Enter night" },
  { seconds: 101, lyrics: "Take my hand" },
  { seconds: 105, lyrics: "We're off to never never land" },
  { seconds: 123, lyrics: "Something's wrong shut the light" },
  { seconds: 125, lyrics: "Heavy thoughts tonight" },
  { seconds: 127, lyrics: "And they aren't of show white" },
  { seconds: 130, lyrics: "Dreams of war dreams of liars" },
  { seconds: 132, lyrics: "Dreams of dragon's fire" },
  { seconds: 134, lyrics: "And of things that will bite" },
  { seconds: 139, lyrics: "Sleep with one eye open" },
  { seconds: 142, lyrics: "Gripping your pillow tight" },
  { seconds: 145, lyrics: "Exit light" },
  { seconds: 149, lyrics: "Enter night" },
  { seconds: 153, lyrics: "Take my hand" },
  { seconds: 157, lyrics: "We're off to never never land" },
  { seconds: 206, lyrics: "Now I lay me down to sleep" },
  { seconds: 209, lyrics: "Pray the lord my soul to keep" },
  { seconds: 213, lyrics: "If I die before I wake" },
  { seconds: 217, lyrics: "Pray the lord my soul to take" },
  { seconds: 221, lyrics: "Hush little baby don't say a word" },
  { seconds: 225, lyrics: "And never mind that noise you heard" },
  { seconds: 229, lyrics: "It's just the beast under your bed" },
  { seconds: 233, lyrics: "In your closet in your head" },
  { seconds: 236, lyrics: "Exit light" },
  { seconds: 240, lyrics: "Enter night" },
  { seconds: 244, lyrics: "Grain of sand" },
  { seconds: 248, lyrics: "Exit light" },
  { seconds: 252, lyrics: "Enter night" },
  { seconds: 256, lyrics: "Take my hand" },
  { seconds: 259, lyrics: "We're off to never never land" },
  { seconds: 271, lyrics: "Yeah Yeah " },
  { seconds: 277, lyrics: "Yo Yo " },
  { seconds: 284, lyrics: "We're off to never never land" },
  { seconds: 286, lyrics: "Take my hand" },
];
